package com.toi.utils;

import com.toi.config.ConfigReader;
import jakarta.activation.DataHandler;
import jakarta.activation.FileDataSource;
import jakarta.mail.*;
import jakarta.mail.internet.*;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.File;
import java.util.Properties;

/**
 * EmailUtils — sends the Extent HTML report via Gmail SMTP after suite execution.
 */
public class EmailUtils {

    private static final Logger log = LogManager.getLogger(EmailUtils.class);

    private EmailUtils() {}

    public static void sendReport(String reportFilePath, int passed, int failed, int skipped) {
        if (!Boolean.parseBoolean(ConfigReader.get("email.enabled", "false"))) {
            log.info("Email reporting disabled — skipping.");
            return;
        }

        String host     = ConfigReader.get("email.smtp.host");
        String port     = ConfigReader.get("email.smtp.port");
        String from     = ConfigReader.get("email.from");
        String password = ConfigReader.get("email.password");
        String to       = ConfigReader.get("email.to");
        String subject  = ConfigReader.get("email.subject");

        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", host);
        props.put("mail.smtp.port", port);
        props.put("mail.smtp.ssl.trust", host);

        Session session = Session.getInstance(props, new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(from, password);
            }
        });

        try {
            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress(from));
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
            message.setSubject(subject);

            // ── Email body ────────────────────────────────────────────────────
            int total = passed + failed + skipped;
            String status = (failed == 0) ? "✅ PASSED" : "❌ FAILED";
            String bodyHtml = "<html><body style='font-family:Arial,sans-serif;'>"
                + "<h2 style='color:#c0392b;'>TOI iOS App — Sanity Test Report</h2>"
                + "<p><b>Build:</b> 17.1.0 &nbsp;|&nbsp; <b>Status:</b> " + status + "</p>"
                + "<table border='1' cellpadding='8' cellspacing='0' style='border-collapse:collapse;width:400px;'>"
                + "<tr style='background:#2c3e50;color:white;'><th>Metric</th><th>Count</th></tr>"
                + "<tr><td>Total Tests</td><td>" + total + "</td></tr>"
                + "<tr style='background:#27ae60;color:white;'><td><b>Passed</b></td><td><b>" + passed + "</b></td></tr>"
                + (failed > 0 ? "<tr style='background:#e74c3c;color:white;'><td><b>Failed</b></td><td><b>" + failed + "</b></td></tr>" : "<tr><td>Failed</td><td>" + failed + "</td></tr>")
                + "<tr><td>Skipped</td><td>" + skipped + "</td></tr>"
                + "</table>"
                + "<br><p>Full HTML report is attached. Please open <b>SanityReport.html</b> in a browser.</p>"
                + "<p style='color:gray;font-size:12px;'>Generated by TOI iOS Automation Framework — " + java.time.LocalDateTime.now() + "</p>"
                + "</body></html>";

            // ── Multipart: body + attachment ──────────────────────────────────
            MimeBodyPart textPart = new MimeBodyPart();
            textPart.setContent(bodyHtml, "text/html; charset=utf-8");

            Multipart multipart = new MimeMultipart();
            multipart.addBodyPart(textPart);

            File reportFile = new File(reportFilePath);
            if (reportFile.exists()) {
                MimeBodyPart attachPart = new MimeBodyPart();
                attachPart.setDataHandler(new DataHandler(new FileDataSource(reportFile)));
                attachPart.setFileName("SanityReport.html");
                multipart.addBodyPart(attachPart);
                log.info("Attaching report: {}", reportFile.getAbsolutePath());
            } else {
                log.warn("Report file not found, sending email without attachment: {}", reportFilePath);
            }

            message.setContent(multipart);
            Transport.send(message);
            log.info("✅ Sanity report email sent to: {}", to);

        } catch (MessagingException e) {
            log.error("Failed to send report email: {}", e.getMessage(), e);
        }
    }
}
